version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: cpy
    versions:
    - 8.1.1
  - dependency-name: eslint-plugin-react-hooks
    versions:
    - 4.1.0
